---
# tasks/Ubuntu/rabbit.yml: Deploy RabbitMQ
# Specific to Ubuntu

- include_vars: "{{ ansible_distribution }}.yml"

- name: Ensure the RabbitMQ APT repo GPG key is present
  apt_key:
    url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    state: present

- name: Ensure the RabbitMQ APT repo is present
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main"
    filename: rabbitmq
    state: present
    update_cache: true

- name: Ensure the Erlang APT repo GPG key is present
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

    #- name: Ensure compatible Erlang repo
    #  apt:
    #    deb: http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_20.3.6-1~ubuntu~xenial_amd64.deb

    # Current Erlang version is not compatible with RMQ, so workaround that a bit
- name: Ensure the Erlang APT repo is present
  apt_repository:
    repo: "deb https://packages.erlang-solutions.com/ubuntu {{ ansible_distribution_release }} contrib"
    filename: erlang
    state: present
    update_cache: true

- name: Pin Erlang version to 20.3.6
  copy:
    src: erlang.aptpin
    dest: /etc/apt/preferences.d/erlang

- name: Ensure RabbitMQ is installed
  apt:
    name: rabbitmq-server
    state: "{{ rabbitmq_pkg_state }}"
    cache_valid_time: 600
    update_cache: true
